### ISSUE TITLE
#TK38 Añadir icono sesion 

### ISSUE THREAD

**Issue by FernandaACastillo** [ISPC-23/FullStack2024#27]
Añadir en el header el icono que navegará a la page de registro/logueo
Historia de usuario #US07 y #US08

**Comment by fedekrenn** [comment]
Se mueve al sprint 2 ya que es necesario detectar el estado del usuario (Logueado/no logueado) para así mostrar el ícono correcto

**Comment by fedekrenn** [comment]
Se realiza ok
