### ISSUE TITLE
#TK68 - Data Binding

### ISSUE THREAD

**Issue by fedekrenn** [ISPC-23/FullStack2024#69]
Logra implementar el enlace de datos (data binding) para la galería de productos/servicios y detalle de productos/servicios, dashboard y demás componentes que lo requieran.
Historia de usuario #US01

**Comment by Verosolc30** [comment]
Enlace de datos (Data Binding) de galeria de productos. ok

**Comment by blasichea** [comment]
Data binding de product-detail OK

**Comment by fedekrenn** [comment]
Tarea finalizada por los compañeros asignados
